server:
  port: 8080

spring:
  application:
    name: url-shortener
  # Redis configuration  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

logging:
  level:
    root: INFO
    ai.shreds: DEBUG